/*
 * KavaRef - A modernizing Java Reflection with Kotlin.
 * Copyright (C) 2019 HighCapable
 * https://github.com/HighCapable/KavaRef
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2025/5/16.
 */
@file:Suppress("UNCHECKED_CAST", "UnnecessaryVariable")

package com.highcapable.kavaref.resolver.processor

import com.highcapable.kavaref.condition.ConstructorCondition
import com.highcapable.kavaref.condition.FieldCondition
import com.highcapable.kavaref.condition.MethodCondition
import com.highcapable.kavaref.condition.base.ExecutableCondition
import com.highcapable.kavaref.condition.base.MemberCondition
import com.highcapable.kavaref.condition.matcher.base.TypeMatcher
import com.highcapable.kavaref.condition.type.Modifiers
import com.highcapable.kavaref.condition.type.VagueType
import com.highcapable.kavaref.extension.classOf
import com.highcapable.kavaref.extension.toClass
import com.highcapable.kavaref.generated.KavaRefProperties
import com.highcapable.kavaref.platform.ExecutableAccessor
import com.highcapable.kavaref.platform.FieldAccessor
import com.highcapable.kavaref.platform.MemberAccessor
import com.highcapable.kavaref.platform.MethodAccessor
import com.highcapable.kavaref.resolver.ConstructorResolver
import com.highcapable.kavaref.resolver.FieldResolver
import com.highcapable.kavaref.resolver.MethodResolver
import com.highcapable.kavaref.resolver.base.InstanceAwareResolver
import com.highcapable.kavaref.resolver.base.MemberResolver
import com.highcapable.kavaref.runtime.KavaRefRuntime
import java.lang.reflect.Constructor
import java.lang.reflect.Field
import java.lang.reflect.Member
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import java.lang.reflect.Type
import kotlin.reflect.KClass

/**
 * The core implementation of member resolution.
 */
object MemberProcessor {

    private const val PRODUCT_DESCRIPTION = "\n====== Generated by KavaRef ${KavaRefProperties.PROJECT_KAVAREF_BOM_VERSION} ======\n"

    private const val FAILURE_MARK = "[!]"
    private const val NOT_EVALUATED_MARK = "[-]"

    /**
     * Global [Resolver] used by KavaRef to resolve members.
     *
     * You can change this resolver to use a custom member resolver, which will affect global behavior.
     */
    @JvmStatic
    var globalResolver: Resolver = Resolver()

    /**
     * Resolver class for resolving members.
     *
     * Provides methods to resolve fields, methods, and constructors of a class.
     *
     * You can inherit this class to implement a custom member parser,
     * and override the [getDeclaredFields], [getDeclaredMethods] and
     * [getDeclaredConstructors] methods to implement custom member resolution logic.
     */
    open class Resolver {

        /**
         * Resolves fields of the specified class [T].
         * @param declaringClass the class to resolve fields from.
         * @return [List]<[Field]>
         */
        open fun <T : Any> getDeclaredFields(declaringClass: Class<T>): List<Field> =
            runCatching { declaringClass.declaredFields.toList() }.onFailure {
                KavaRefRuntime.warn("Failed to get declared fields in $declaringClass because an exception was thrown", it)
            }.getOrNull() ?: emptyList()

        /**
         * Resolves methods of the specified class [T].
         * @param declaringClass the class to resolve methods from.
         * @return [List]<[Method]>
         */
        open fun <T : Any> getDeclaredMethods(declaringClass: Class<T>): List<Method> =
            runCatching { declaringClass.declaredMethods.toList() }.onFailure {
                KavaRefRuntime.warn("Failed to get declared methods in $declaringClass because an exception was thrown", it)
            }.getOrNull() ?: emptyList()

        /**
         * Resolves constructors of the specified class [T].
         * @param declaringClass the class to resolve constructors from.
         * @return [List]<[Constructor]<[T]>>
         */
        open fun <T : Any> getDeclaredConstructors(declaringClass: Class<T>): List<Constructor<T>> =
            runCatching { declaringClass.declaredConstructors.filterIsInstance<Constructor<T>>() }.onFailure {
                KavaRefRuntime.warn("Failed to get declared constructors in $declaringClass because an exception was thrown", it)
            }.getOrNull() ?: emptyList()
    }

    /**
     * Resolves members with current [condition] and [configuration].
     * @param condition the condition to resolve members.
     * @param configuration the configuration to resolve members, must not be null.
     * @return [List]<[R]>
     */
    internal inline fun <reified M : Member, reified R : MemberResolver<M, T>, T : Any> resolve(
        condition: MemberCondition<M, R, T>,
        configuration: MemberCondition.Configuration<T>?
    ): List<R> {
        require(configuration != null) {
            "You must provide a configuration to resolve the member, use build(configuration)."
        }

        val context = ResolveContext(configuration)
        return when (condition) {
            is MethodCondition -> resolveInClass(context, condition, configuration) { declaringClass ->
                methodFilters(context, condition, configuration, declaringClass)
            }
            is ConstructorCondition -> constructorFilters(context, condition, configuration).ifEmpty {
                throwIfNotOptional(context, condition, configuration)
            }
            is FieldCondition -> resolveInClass(context, condition, configuration) { declaringClass ->
                fieldFilters(context, condition, configuration, declaringClass)
            }
            else -> error("Unsupported condition type: $condition")
        } as List<R>
    }

    private fun <M : Member, R : MemberResolver<M, T>, T : Any> resolveInClass(
        context: ResolveContext,
        condition: MemberCondition<M, R, T>,
        configuration: MemberCondition.Configuration<T>,
        result: (declaringClass: Class<*>) -> List<R>
    ): List<R> {
        configuration.declaringClass.searchClasses(condition.superclassMode(configuration)).forEach { declaringClass ->
            result(declaringClass).takeIf { it.isNotEmpty() }?.let { return it }
        }

        return throwIfNotOptional(context, condition, configuration)
    }

    /**
     * Gets the classes to be searched in order by the superclass [mode].
     *
     * The superclasses are searched until `java.lang.Object` (including `java.lang.Object` itself),
     * then all the interfaces, a sub-interface is always searched before its super-interfaces.
     */
    private fun Class<*>.searchClasses(mode: MemberCondition.Configuration.Superclass) = sequence {
        val superclasses = generateSequence(this@searchClasses) { it.superclass }
        when (mode) {
            MemberCondition.Configuration.Superclass.NO -> yield(this@searchClasses)
            MemberCondition.Configuration.Superclass.NORMAL -> yieldAll(superclasses)
            MemberCondition.Configuration.Superclass.INCLUDE_INTERFACES -> {
                yieldAll(superclasses)
                yieldAll(superclasses.interfaces())
            }
        }
    }

    /** Gets all the interfaces of these classes, a sub-interface is always before its super-interfaces. */
    private fun Sequence<Class<*>>.interfaces(): List<Class<*>> {
        val collected = linkedSetOf<Class<*>>()
        val queue = ArrayDeque(flatMap { it.interfaces.asSequence() }.toList())
        while (queue.isNotEmpty()) queue.removeFirst().takeIf { collected.add(it) }?.let { queue.addAll(it.interfaces) }

        val remaining = collected.toMutableList()
        return buildList {
            while (remaining.isNotEmpty()) {
                val next = remaining.first { candidate -> remaining.none { it !== candidate && candidate.isAssignableFrom(it) } }
                add(next)
                remaining.remove(next)
            }
        }
    }

    private fun <T : Any> methodFilters(
        context: ResolveContext,
        condition: MethodCondition<T>,
        configuration: MemberCondition.Configuration<T>,
        declaringClass: Class<*>
    ): List<MethodResolver<T>> = configuration.currentProcessorResolver.getDeclaredMethods(declaringClass)
        .asSequence()
        .baseFilters(context, condition, configuration)
        .executableFilters(context, condition, configuration)
        .asAccess<MethodAccessor>()
        .filter(configuration, MethodCondition.RETURN_TYPE, condition.returnType) { key, value ->
            value.returnType == key.toTypeClass(context, noVague = "Method: returnType")
        }
        .filterCondition(context, configuration, MethodCondition.RETURN_TYPE_CONDITION, condition.returnTypeCondition) { key, value ->
            key(value.returnType)
        }
        .filter(configuration, MethodCondition.GENERIC_RETURN_TYPE, condition.genericReturnType) { key, value ->
            key.matches(value.genericReturnType)
        }
        .filterCondition(context, configuration, MethodCondition.GENERIC_RETURN_TYPE_CONDITION, condition.genericReturnTypeCondition) { key, value ->
            key(value.genericReturnType)
        }
        .filter(configuration, MethodCondition.IS_BRIDGE, condition.isBridge) { key, value -> value.isBridge == key }
        .filter(configuration, MethodCondition.IS_BRIDGE_NOT, condition.isBridgeNot) { key, value -> value.isBridge != key }
        .filter(configuration, MethodCondition.IS_DEFAULT, condition.isDefault) { key, value -> value.isDefault == key }
        .filter(configuration, MethodCondition.IS_DEFAULT_NOT, condition.isDefaultNot) { key, value -> value.isDefault != key }
        .filter(configuration, MethodCondition.DEFAULT_VALUE, condition.defaultValue) { key, value ->
            // The default value of an annotation method can be an array, compare its content instead of its reference.
            arrayOf(value.defaultValue).contentDeepEquals(arrayOf(key))
        }
        .filterCondition(context, configuration, MethodCondition.DEFAULT_VALUE_CONDITION, condition.defaultValueCondition) { key, value ->
            key(value.defaultValue)
        }
        .endAccess<Method>()
        .resolve(configuration)

    private fun <T : Any> constructorFilters(
        context: ResolveContext,
        condition: ConstructorCondition<T>,
        configuration: MemberCondition.Configuration<T>
    ): List<ConstructorResolver<T>> = configuration.currentProcessorResolver.getDeclaredConstructors(configuration.declaringClass)
        .asSequence()
        .baseFilters(context, condition, configuration)
        .executableFilters(context, condition, configuration)
        .endAccess<Constructor<T>>()
        .resolve(configuration)

    private fun <T : Any> fieldFilters(
        context: ResolveContext,
        condition: FieldCondition<T>,
        configuration: MemberCondition.Configuration<T>,
        declaringClass: Class<*>
    ): List<FieldResolver<T>> = configuration.currentProcessorResolver.getDeclaredFields(declaringClass)
        .asSequence()
        .baseFilters(context, condition, configuration)
        .asAccess<FieldAccessor>()
        .filter(configuration, FieldCondition.IS_ENUM_CONSTANT, condition.isEnumConstant) { key, value -> value.isEnumConstant == key }
        .filter(configuration, FieldCondition.IS_ENUM_CONSTANT_NOT, condition.isEnumConstantNot) { key, value -> value.isEnumConstant != key }
        .filter(configuration, FieldCondition.TYPE, condition.type) { key, value ->
            value.type == key.toTypeClass(context, noVague = "Field: type")
        }
        .filterCondition(context, configuration, FieldCondition.TYPE_CONDITION, condition.typeCondition) { key, value -> key(value.type) }
        .filter(configuration, FieldCondition.GENERIC_TYPE, condition.genericType) { key, value -> key.matches(value.genericType) }
        .filterCondition(context, configuration, FieldCondition.GENERIC_TYPE_CONDITION, condition.genericTypeCondition) { key, value ->
            key(value.genericType)
        }
        .endAccess<Field>()
        .resolve(configuration)

    private fun <M : Member, T : Any> Sequence<M>.baseFilters(
        context: ResolveContext,
        condition: MemberCondition<*, *, *>,
        configuration: MemberCondition.Configuration<T>
    ) = this.beginAccess()
        .filter(configuration, MemberCondition.NAME, condition.name) { key, value -> value.name == key }
        .filterCondition(context, configuration, MemberCondition.NAME_CONDITION, condition.nameCondition) { key, value -> key(value.name) }
        .filter(configuration, MemberCondition.MODIFIERS, condition.modifiers) { key, value ->
            key.all { it.matches(value.sourceModifiers) }
        }
        .filter(configuration, MemberCondition.MODIFIERS_NOT, condition.modifiersNot) { key, value ->
            key.none { it.matches(value.sourceModifiers) }
        }
        .filterCondition(context, configuration, MemberCondition.MODIFIERS_CONDITION, condition.modifiersCondition) { key, value ->
            key(Modifiers.matching(value.sourceModifiers))
        }
        .filter(configuration, MemberCondition.IS_SYNTHETIC, condition.isSynthetic) { key, value -> value.isSynthetic == key }
        .filter(configuration, MemberCondition.IS_SYNTHETIC_NOT, condition.isSyntheticNot) { key, value -> value.isSynthetic != key }
        .filter(configuration, MemberCondition.ANNOTATIONS, condition.annotations) { key, value ->
            val annotations = value.annotations.map { it.annotationClass.java }
            compareAnnotationTypes(context, key, annotations, noVague = "Member: annotations")
        }
        .filter(configuration, MemberCondition.ANNOTATIONS_NOT, condition.annotationsNot) { key, value ->
            val annotations = value.annotations.map { it.annotationClass.java }
            compareAnnotationTypesNot(context, key, annotations, noVague = "Member: annotationsNot")
        }
        .filterEmpty(configuration, condition, MemberCondition.EMPTY_ANNOTATIONS, MemberCondition.EMPTY_ANNOTATIONS_NOT) { it.annotations.size }
        .filter(configuration, MemberCondition.GENERIC_STRING, condition.genericString) { key, value -> value.genericString == key }

    private fun <T : Any> Sequence<MemberAccessor>.executableFilters(
        context: ResolveContext,
        condition: ExecutableCondition<*, *, *>,
        configuration: MemberCondition.Configuration<T>
    ) = this.asAccess<ExecutableAccessor>()
        .filter(configuration, ExecutableCondition.PARAMETERS, condition.parameters) { key, value ->
            compareElementTypes(context, key, value.parameterTypes.toList())
        }
        .filter(configuration, ExecutableCondition.PARAMETERS_NOT, condition.parametersNot) { key, value ->
            compareElementTypesNot(context, key, value.parameterTypes.toList())
        }
        .filterCondition(context, configuration, ExecutableCondition.PARAMETERS_CONDITION, condition.parametersCondition) { key, value ->
            key(value.parameterTypes.toList())
        }
        .filter(configuration, ExecutableCondition.PARAMETER_COUNT, condition.parameterCount) { key, value -> value.parameterCount == key }
        .filterCondition(context, configuration, ExecutableCondition.PARAMETER_COUNT_CONDITION, condition.parameterCountCondition) { key, value ->
            key(value.parameterCount)
        }
        .filter(configuration, ExecutableCondition.TYPE_PARAMETERS, condition.typeParameters) { key, value ->
            compareMatcherTypes(key, value.typeParameters.toList())
        }
        .filter(configuration, ExecutableCondition.TYPE_PARAMETERS_NOT, condition.typeParametersNot) { key, value ->
            !compareMatcherTypes(key, value.typeParameters.toList())
        }
        .filterEmpty(configuration, condition, ExecutableCondition.EMPTY_TYPE_PARAMETERS, ExecutableCondition.EMPTY_TYPE_PARAMETERS_NOT) {
            it.typeParameters.size
        }
        .filter(configuration, ExecutableCondition.EXCEPTION_TYPES, condition.exceptionTypes) { key, value ->
            compareElementTypes(context, key, value.exceptionTypes.toList())
        }
        .filter(configuration, ExecutableCondition.EXCEPTION_TYPES_NOT, condition.exceptionTypesNot) { key, value ->
            compareElementTypesNot(context, key, value.exceptionTypes.toList())
        }
        .filterEmpty(configuration, condition, ExecutableCondition.EMPTY_EXCEPTION_TYPES, ExecutableCondition.EMPTY_EXCEPTION_TYPES_NOT) {
            it.exceptionTypes.size
        }
        .filter(configuration, ExecutableCondition.GENERIC_EXCEPTION_TYPES, condition.genericExceptionTypes) { key, value ->
            compareMatcherTypes(key, value.genericExceptionTypes.toList())
        }
        .filter(configuration, ExecutableCondition.GENERIC_EXCEPTION_TYPES_NOT, condition.genericExceptionTypesNot) { key, value ->
            !compareMatcherTypes(key, value.genericExceptionTypes.toList())
        }
        .filterEmpty(configuration, condition, ExecutableCondition.EMPTY_GENERIC_EXCEPTION_TYPES, ExecutableCondition.EMPTY_GENERIC_EXCEPTION_TYPES_NOT) {
            it.genericExceptionTypes.size
        }
        .filter(configuration, ExecutableCondition.GENERIC_PARAMETERS, condition.genericParameters) { key, value ->
            compareMatcherTypes(key, value.genericParameterTypes.toList())
        }
        .filter(configuration, ExecutableCondition.GENERIC_PARAMETERS_NOT, condition.genericParametersNot) { key, value ->
            !compareMatcherTypes(key, value.genericParameterTypes.toList())
        }
        .filter(configuration, ExecutableCondition.IS_VAR_ARGS, condition.isVarArgs) { key, value -> value.isVarArgs == key }
        .filter(configuration, ExecutableCondition.IS_VAR_ARGS_NOT, condition.isVarArgsNot) { key, value -> value.isVarArgs != key }
        .filter(configuration, ExecutableCondition.PARAMETER_ANNOTATIONS, condition.parameterAnnotations) { key, value ->
            val annotations = value.parameterAnnotations.map { it.map { e -> e.annotationClass.java } }
            compareAnnotationTypes(context, key, annotations, noVague = "Executable: parameterAnnotations")
        }
        .filter(configuration, ExecutableCondition.PARAMETER_ANNOTATIONS_NOT, condition.parameterAnnotationsNot) { key, value ->
            val annotations = value.parameterAnnotations.map { it.map { e -> e.annotationClass.java } }
            compareAnnotationTypesNot(context, key, annotations, noVague = "Executable: parameterAnnotationsNot")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_RETURN_TYPE, condition.annotatedReturnType) { key, value ->
            val annotations = value.annotatedReturnType.annotations.map { it.annotationClass.java }
            compareAnnotationTypes(context, key, annotations, noVague = "Executable: annotatedReturnType")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_RETURN_TYPE_NOT, condition.annotatedReturnTypeNot) { key, value ->
            val annotations = value.annotatedReturnType.annotations.map { it.annotationClass.java }
            compareAnnotationTypesNot(context, key, annotations, noVague = "Executable: annotatedReturnTypeNot")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_RECEIVER_TYPE, condition.annotatedReceiverType) { key, value ->
            val annotations = value.annotatedReceiverType?.annotations.orEmpty().map { it.annotationClass.java }
            compareAnnotationTypes(context, key, annotations, noVague = "Executable: annotatedReceiverType")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_RECEIVER_TYPE_NOT, condition.annotatedReceiverTypeNot) { key, value ->
            val annotations = value.annotatedReceiverType?.annotations.orEmpty().map { it.annotationClass.java }
            compareAnnotationTypesNot(context, key, annotations, noVague = "Executable: annotatedReceiverTypeNot")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_PARAMETER_TYPES, condition.annotatedParameterTypes) { key, value ->
            val annotations = value.annotatedParameterTypes.map { it.annotations.map { e -> e.annotationClass.java } }
            compareAnnotationTypes(context, key, annotations, noVague = "Executable: annotatedParameterTypes")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_PARAMETER_TYPES_NOT, condition.annotatedParameterTypesNot) { key, value ->
            val annotations = value.annotatedParameterTypes.map { it.annotations.map { e -> e.annotationClass.java } }
            compareAnnotationTypesNot(context, key, annotations, noVague = "Executable: annotatedParameterTypesNot")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_EXCEPTION_TYPES, condition.annotatedExceptionTypes) { key, value ->
            val annotations = value.annotatedExceptionTypes.map { it.annotations.map { e -> e.annotationClass.java } }
            compareAnnotationTypes(context, key, annotations, noVague = "Executable: annotatedExceptionTypes")
        }
        .filter(configuration, ExecutableCondition.ANNOTATED_EXCEPTION_TYPES_NOT, condition.annotatedExceptionTypesNot) { key, value ->
            val annotations = value.annotatedExceptionTypes.map { it.annotations.map { e -> e.annotationClass.java } }
            compareAnnotationTypesNot(context, key, annotations, noVague = "Executable: annotatedExceptionTypesNot")
        }

    private inline fun <reified M : Member, reified R : MemberResolver<M, T>, T : Any> Sequence<M>.resolve(
        configuration: MemberCondition.Configuration<T>
    ) = when (M::class) {
        Method::class -> map { MethodResolver<T>(it as Method).apply(configuration) }
        Constructor::class -> map { ConstructorResolver(it as Constructor<T>).apply(configuration) }
        Field::class -> map { FieldResolver<T>(it as Field).apply(configuration) }
        else -> error("Unsupported member type: $this")
    }.toList() as List<R>

    private fun <M : Member, R : MemberResolver<M, T>, T : Any> throwIfNotOptional(
        context: ResolveContext,
        condition: MemberCondition<M, R, T>,
        configuration: MemberCondition.Configuration<T>
    ): List<R> {
        val exceptionNote = "If you want to ignore this exception, add optional() to your condition."
        val superclassMode = condition.superclassMode(configuration)
        val superclassNote = when (superclassMode) {
            MemberCondition.Configuration.Superclass.NO -> ""
            MemberCondition.Configuration.Superclass.NORMAL -> " (Also tried in superclasses)"
            MemberCondition.Configuration.Superclass.INCLUDE_INTERFACES -> " (Also tried in superclasses and interfaces)"
        }

        val memberSuggestion = if (superclassMode == MemberCondition.Configuration.Superclass.NO)
            "Members in superclasses are not reflected in the current class, you can try adding superclass() to your condition and try again"
        else "Check if the conditions are correct and valid, and try again"

        val conditionTable = buildConditionTable(context, condition, configuration)
        val isOptional = configuration.optional != MemberCondition.Configuration.Optional.NO
        val message = when (condition) {
            is MethodCondition -> "No method found matching the condition for the current class$superclassNote.\n" +
                conditionTable + "\n" +
                "Suggestion: $memberSuggestion"
            is ConstructorCondition -> "No constructor found matching the condition for the current class.\n" +
                conditionTable + "\n" +
                "Suggestion: Constructors are not inherited from the superclass, check if the conditions are correct and valid, and try again"
            is FieldCondition -> "No field found matching the condition for the current class$superclassNote.\n" +
                conditionTable + "\n" +
                "Suggestion: $memberSuggestion"
            else -> error("Unsupported condition type: $condition")
        }

        // List every exception with its stack trace under its condition, keep the same order as the condition table.
        val failuresNote = condition.conditionStringMap.keys.mapNotNull { name -> context.failures[name]?.let { name to it } }
            .joinToString("\n") { (name, failures) ->
                "[$name]\n" + failures.joinToString("\n") { (member, throwable) ->
                    "- ${member.toStringIgnore()}\n${throwable.stackTraceToString().trim()}"
                }
            }.takeIf { it.isNotEmpty() }?.let { "$FAILURE_MARK Exceptions thrown by runtime conditions:\n$it\n" }.orEmpty()
        val exceptionMessage = "$message\n$failuresNote$exceptionNote\n$PRODUCT_DESCRIPTION"

        return if (!isOptional) throw when (condition) {
            is MethodCondition -> NoSuchMethodException(exceptionMessage)
            is ConstructorCondition -> NoSuchMethodException(exceptionMessage)
            is FieldCondition -> NoSuchFieldException(exceptionMessage)
            else -> error("Unsupported condition type: $condition")
        } else {
            if (configuration.optional == MemberCondition.Configuration.Optional.NOTICE)
                KavaRefRuntime.warn("$message\n$failuresNote".trim())
            emptyList()
        }
    }

    private inline fun <reified M : Member, T : Any> MemberResolver<M, T>.apply(configuration: MemberCondition.Configuration<T>) =
        apply { configuration.memberInstance?.let { if (this is InstanceAwareResolver) of(it) } }

    private fun <T, R> Sequence<T>.filter(
        configuration: MemberCondition.Configuration<*>,
        name: String,
        key: R?,
        predicate: (key: R, value: T) -> Boolean
    ) = filter { condition ->
        val predicateKey = if (key is Collection<*>)
            key.takeIf { it.isNotEmpty() }
        else key

        predicateKey?.let {
            val result = predicate(it, condition)
            if (configuration.shouldLogFilterDebug()) {
                val sKey = VagueType.format(it)?.toStringIgnore()
                val sValue = condition?.toStringIgnore()

                KavaRefRuntime.debug("[FILTER] [${if (result) "HIT" else "MISS"}] $name: $sKey [RESOLVED] $sValue")
            }

            result
        } ?: true
    }

    /**
     * Filters by a runtime condition, an exception thrown by it is treated as not matched
     * and recorded in [context] to be reported if no member is found.
     */
    private fun <T : MemberAccessor, R> Sequence<T>.filterCondition(
        context: ResolveContext,
        configuration: MemberCondition.Configuration<*>,
        name: String,
        key: R?,
        predicate: (key: R, value: T) -> Boolean
    ) = filter(configuration, name, key) { conditionKey, value ->
        context.markEvaluated(name)
        runCatching { predicate(conditionKey, value) }.getOrElse {
            context.addFailure(name, value.member, it)
            if (configuration.shouldLogFilterDebug())
                KavaRefRuntime.debug("[FILTER] [ERROR] $name: ${value.member.toStringIgnore()}", it)
            false
        }
    }

    private fun <T> Sequence<T>.filterEmpty(
        configuration: MemberCondition.Configuration<*>,
        condition: MemberCondition<*, *, *>,
        name: String,
        notName: String,
        size: (T) -> Int
    ) = filter(configuration, name, name.takeIf { it in condition.emptyConditions }) { _, value -> size(value) == 0 }
        .filter(configuration, notName, notName.takeIf { it in condition.emptyConditions }) { _, value -> size(value) > 0 }

    private fun compareElementTypes(
        context: ResolveContext,
        conditionKey: Collection<Any>,
        typesValue: List<Class<*>>
    ): Boolean {
        // If size is different at first, return false.
        if (conditionKey.size != typesValue.size) return false

        var index = 0
        conditionKey.forEach { conditionType ->
            val target = typesValue[index++]
            val expected = conditionType.toTypeClass(context)

            if (expected != classOf<VagueType>() && target != expected)
                return false
        }

        return true
    }

    private fun compareElementTypesNot(
        context: ResolveContext,
        conditionKey: Collection<Any>,
        typesValue: List<Class<*>>
    ) = !conditionKey.hasUnresolvedType(context) && !compareElementTypes(context, conditionKey, typesValue)

    private fun compareAnnotationTypes(
        context: ResolveContext,
        conditionKey: Collection<Any>,
        annotations: List<Class<*>>,
        noVague: String
    ): Boolean {
        // The order of annotations is not defined, compare them as a set.
        if (conditionKey.size != annotations.size) return false
        return conditionKey.mapTo(mutableSetOf()) { it.toTypeClass(context, noVague) } == annotations.toSet()
    }

    private fun compareAnnotationTypesNot(
        context: ResolveContext,
        conditionKey: Collection<Any>,
        annotations: List<Class<*>>,
        noVague: String
    ) = !conditionKey.hasUnresolvedType(context) && !compareAnnotationTypes(context, conditionKey, annotations, noVague)

    @JvmName("compareAnnotationTypesMultiple")
    private fun compareAnnotationTypes(
        context: ResolveContext,
        conditionKey: Collection<Collection<Any>>,
        annotations: List<List<Class<*>>>,
        noVague: String
    ): Boolean {
        if (conditionKey.size != annotations.size) return false
        return conditionKey.zip(annotations).all { (key, value) -> compareAnnotationTypes(context, key, value, noVague) }
    }

    @JvmName("compareAnnotationTypesNotMultiple")
    private fun compareAnnotationTypesNot(
        context: ResolveContext,
        conditionKey: Collection<Collection<Any>>,
        annotations: List<List<Class<*>>>,
        noVague: String
    ) = conditionKey.none { it.hasUnresolvedType(context) } && !compareAnnotationTypes(context, conditionKey, annotations, noVague)

    private fun compareMatcherTypes(
        conditionKey: Collection<TypeMatcher>,
        typesValue: List<Type>
    ): Boolean {
        // If size is different at first, return false.
        if (conditionKey.size != typesValue.size) return false

        var index = 0
        conditionKey.forEach { matcher ->
            val target = typesValue[index++]
            if (!matcher.matches(target))
                return false
        }

        return true
    }

    private fun <T : Any> buildConditionTable(
        context: ResolveContext,
        condition: MemberCondition<*, *, *>,
        configuration: MemberCondition.Configuration<T>
    ) = runCatching {
        fun displayWidth(str: String) = str.sumOf { if (it.code > 127L) 2L else 1L }.toInt()

        fun padDisplay(str: String, targetWidth: Int): String {
            val currentWidth = displayWidth(str)
            val padding = targetWidth - currentWidth
            return if (padding > 0) str + " ".repeat(padding) else str
        }

        val rows = condition.conditionStringMap.mapNotNull { (label, value) ->
            val displayValue = when (value) {
                null -> null
                is Function<*> -> when (label) {
                    in context.failures -> "$FAILURE_MARK (Runtime Condition)"
                    !in context.evaluatedConditions -> "$NOT_EVALUATED_MARK (Runtime Condition)"
                    else -> "(Runtime Condition)"
                }
                is Collection<*> -> if (value.isEmpty()) null else VagueType.format(value)
                else -> VagueType.format(value)
                // Remove the Kotlin reflection warning message.
            }?.toStringIgnore()
            displayValue?.let { label to it }
        }

        if (rows.isEmpty()) return@runCatching configuration.declaringClass.toString()

        val originalLabelWidth = rows.maxOf { displayWidth(it.first) }
        val originalValueWidth = rows.maxOf { displayWidth(it.second) }

        val headerText = configuration.declaringClass.toStringIgnore()
        val headerWidth = displayWidth(headerText)

        val contentWidth = originalLabelWidth + originalValueWidth + 3 // 3: " | "

        // If header is wider, increase value column width.
        val extraPadding = (headerWidth - contentWidth).coerceAtLeast(0)

        val labelWidth = originalLabelWidth
        val valueWidth = originalValueWidth + extraPadding

        val border = "+-${"-".repeat(labelWidth)}-+-${"-".repeat(valueWidth)}-+"
        val headerBorder = "+-${"-".repeat(labelWidth + valueWidth + 3)}-+"
        val header = "| ${padDisplay(headerText, labelWidth + valueWidth + 3)} |"

        val content = rows.joinToString("\n") { (label, value) ->
            "| ${padDisplay(label, labelWidth)} | ${padDisplay(value, valueWidth)} |"
        }

        return@runCatching listOf(headerBorder, header, border, content, border).joinToString("\n")
    }.getOrDefault("${configuration.declaringClass.toStringIgnore()}\nFailed to build condition table.")

    /**
     * Gets the source-level modifiers of the member.
     *
     * The JVM reuses some modifier bits for bridge and varargs methods,
     * so they are masked out by the member type to avoid false matches.
     */
    private val MemberAccessor.sourceModifiers get() = modifiers and when (member) {
        is Method -> Modifier.methodModifiers()
        is Constructor<*> -> Modifier.constructorModifiers()
        is Field -> Modifier.fieldModifiers()
        else -> modifiers
    }

    private fun MemberCondition<*, *, *>.superclassMode(configuration: MemberCondition.Configuration<*>) =
        maxOf(superclassMode, configuration.superclass)

    private val <T : Any> MemberCondition.Configuration<T>.currentProcessorResolver
        get() = processorResolver ?: globalResolver

    private fun MemberCondition.Configuration<*>.shouldLogFilterDebug() =
        this.optional != MemberCondition.Configuration.Optional.SILENT &&
            KavaRefRuntime.logLevel.ordinal <= KavaRefRuntime.LogLevel.DEBUG.ordinal

    private fun Collection<Any>.hasUnresolvedType(context: ResolveContext) =
        context.isOptional && any { it is String && context.resolve(it).isFailure }

    private fun Any.toTypeClass(context: ResolveContext, noVague: String? = null): Class<*> {
        fun Class<*>.parseVagueType() =
            if (this == classOf<VagueType>())
                noVague?.let { error("VagueType is not supported for \"$it\"") } ?: this
            else this

        return when (this) {
            is Class<*> -> this
            is KClass<*> -> this.java
            is String -> if (!context.isOptional)
                context.resolve(this).getOrThrow()
            // If enabled optional mode, use a non-match sentinel when not found so unresolved strings fail closed.
            else context.resolve(this).getOrNull() ?: classOf<UnresolvedTypeSentinel>()
            is VagueType -> javaClass
            else -> error("Unsupported type: $this, the supported types are Class, KClass, String and VagueType")
        }.parseVagueType()
    }

    private fun Sequence<Member>.beginAccess() = map { MemberAccessor(it) }

    private inline fun <reified A : MemberAccessor> Sequence<MemberAccessor>.asAccess() = map {
        when (A::class) {
            FieldAccessor::class -> FieldAccessor(it.member)
            MethodAccessor::class -> MethodAccessor(it.member)
            ExecutableAccessor::class -> ExecutableAccessor(it.member)
            else -> error("Unsupported accessor type: ${A::class}")
        } as A
    }

    private fun <M : Member> Sequence<MemberAccessor>.endAccess() = map { it.member as M }

    private fun Any.toStringIgnore() = toString().replace(" (Kotlin reflection is not available)", "")

    /**
     * The context of a single resolution.
     *
     * Resolves the class names in conditions once, failures are cached too, so the same exception is thrown again on reuse.
     * Also records which runtime conditions are evaluated and the exceptions thrown by them, grouped by the condition name.
     */
    internal class ResolveContext(configuration: MemberCondition.Configuration<*>) {

        private val classLoader = configuration.declaringClass.classLoader
        private val resolved = mutableMapOf<String, Result<Class<*>>>()

        val isOptional = configuration.optional != MemberCondition.Configuration.Optional.NO

        /** The names of runtime conditions that have been evaluated at least once. */
        val evaluatedConditions: Set<String>
            field = mutableSetOf<String>()

        /** The exceptions thrown by runtime conditions, grouped by the condition name. */
        val failures: Map<String, List<Pair<Member, Throwable>>>
            field = linkedMapOf<String, MutableList<Pair<Member, Throwable>>>()

        fun resolve(name: String) = resolved.getOrPut(name) { runCatching { name.toClass(classLoader) } }

        fun markEvaluated(name: String) {
            evaluatedConditions += name
        }

        fun addFailure(name: String, member: Member, throwable: Throwable) {
            failures.getOrPut(name) { mutableListOf() } += member to throwable
        }
    }

    /** Internal sentinel type used when optional string type resolution fails. */
    private class UnresolvedTypeSentinel
}